config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    # A visitor can see the details of a restaurant, with all the reviews related to the restaurant.
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
# frozen_string_literal: true

# Represents a restaurant.
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian].freeze

  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
# frozen_string_literal: true

# Represents a review for a restaurant.
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validate :rating_must_be_an_integer

  private

  def rating_must_be_an_integer
    errors.add(:rating, 'must be an integer') unless rating.is_a? Integer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

# Restaurant controller class
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

# Reviews controller class
class ReviewsController < ApplicationController
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params)
    if @review.save
      redirect_to @restaurant, notice: 'Review created successfully'
    else
      render 'restaurants/show'
    end
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
    @review.restaurant = @restaurant
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">My App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add a restaurant", new_restaurant_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container m-10">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

<%= link_to "Back", restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
      <p><%= restaurant.category %></p>
      <p><%= restaurant.address %></p>
    </li>
  <% end %>
</ul>

<%= link_to "New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to "Back", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p><strong>Category:</strong> <%= @restaurant.category %></p>
<p><strong>Address:</strong> <%= @restaurant.address %></p>
<p><strong>Phone Number:</strong> <%= @restaurant.phone_number %></p>

<%= simple_form_for([@restaurant, @restaurant.reviews.build]) do |f| %>
  <h2>Add a review</h2>
  <%= f.input :content, label: "Content", input_html: { class: "form-control" } %>
  <%= f.input :rating, label: "Rating", collection: (0..5), input_html: { class: "form-control" } %>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<h2>Reviews</h2>
<% if @restaurant.reviews.any? %>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <p><%= review.content %></p>
        <div class="stars">
          <% (1..5).each do |i| %>
            <% if review.rating&.>= i %>
              <span class="star checked"><i class="fas fa-star"></i></span>
            <% else %>
              <span class="star"><i class="far fa-star"></i></span>
            <% end %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No reviews yet</p>
<% end %>
</ul>

<%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-secondary" %> |
<%= link_to "Back", restaurants_path, class: "btn btn-secondary" %>